{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_2():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_2.py:5: AssertionError"}, "start": 1639816810149, "stop": 1639816810149, "uuid": "867fa53f-f897-4532-b576-37d90687a30c", "historyId": "2e39e4b605360da6fe5721fc2f8e6e53", "testCaseId": "c582a42fd310f1877e0de791e5abbe5d", "fullName": "test_2#test_2", "labels": [{"name": "suite", "value": "test_2"}, {"name": "host", "value": "Ani-PC"}, {"name": "thread", "value": "8160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2"}]}